module OMParser

import Absyn, MetaModelica, ImmutableList
#= For searching files.. =#
import Glob
using MetaModelica

#import Settings
const INSTALLATION_DIRECTORY_PATH = realpath(realpath(dirname(Base.find_package("OMParser")) * "/../"))

#Shared path
const SHARED_DIRECTORY_PATH = realpath(string(INSTALLATION_DIRECTORY_PATH, "/lib/ext"))

struct ParseError
end

function isDerCref(exp::Absyn.Exp)::Bool
  @match exp begin
    Absyn.CALL(Absyn.CREF_IDENT("der",  nil()), Absyn.FUNCTIONARGS(Absyn.CREF(__) <|  nil(),  nil()), nil())  => true
    _ => false
  end
end

"""
  This function finds libraries built by the user or by the CI
"""
function _locateSharedParserLibrary(directoryToSearchIn)
  local res = Glob.glob("*",  joinpath(directoryToSearchIn, "lib"))
  local results = []
  for p in res
    push!(results, Glob.glob("*",  joinpath(directoryToSearchIn, p)))
  end
  #= Locate DLL =#
  if Sys.islinux()
    for r in results
      for p in r
        if occursin("libomparse-julia.so", p)
          return p
        end
      end
    end
  elseif Sys.iswindows()
    for r in results
      for p in r
        if occursin("libomparse-julia.dll", p)
          return p
        end
      end
    end
  else #= Assume apple=#
    for r in results
      for p in r
        if occursin("libomparse-julia.dylib", p)
          return p
        end
      end
    end
  end
end

"""
  This function finds precompiled paths 
"""
function locateSharedParserLibrary(directoryToSearchIn)
  local res = Glob.glob("*",  joinpath(directoryToSearchIn, "shared"))
  local results = []
  for p in res
    push!(results, Glob.glob("*",  joinpath(directoryToSearchIn, p)))
  end
  #= Locate DLL =#
  if Sys.islinux()
    for r in results
      for p in r
        if occursin("libomparse-julia.so", p)
          return p
        end
      end
    end    
  elseif Sys.iswindows()
    for r in results
      for p in r
        if occursin("libomparse-julia.dll", p)
          return p
        end
      end
    end
  else #= Assume apple=#
    for r in results
      for p in r
        if occursin("libomparse-julia.dylib", p)
          return p
        end
      end
    end
  end
end

const _libpath = if Sys.iswindows()
  _locateSharedParserLibrary(INSTALLATION_DIRECTORY_PATH)
elseif Sys.islinux()
  _locateSharedParserLibrary(INSTALLATION_DIRECTORY_PATH)
elseif Sys.isapple()
  _locateSharedParserLibrary(INSTALLATION_DIRECTORY_PATH)
else
  throw("Your system is not supported. Supported Systems are Linux, macOS and Windows.")
end

#= Lib path for externally downloaded parser libraries =#
const libpath = if Sys.iswindows()
  locateSharedParserLibrary(SHARED_DIRECTORY_PATH)
elseif Sys.islinux()
  locateSharedParserLibrary(SHARED_DIRECTORY_PATH)
elseif Sys.isapple()
  locateSharedParserLibrary(SHARED_DIRECTORY_PATH)
else
  throw("Your system is not supported. Supported Systems are Linux, macOS and Windows.")
end


#= If there exists a prebuilt library we use that. Otherwise we use the precompiled binary generated by Pkg.build =#
const installedLibPath = if _libpath != nothing
    _libpath
  else
    libpath
end

function parseFile(fileName::String, acceptedGram::Int64 = 1)::Absyn.Program
  local res = ccall((:parseFile, installedLibPath), Any, (String, Int64), fileName, acceptedGram)
  if res == nothing
    throw(ParseError())
  end
  res
end


end
