module OMParser

using MetaModelica

import Absyn, ImmutableList

"""
The path were the package is located.
"""
const INSTALLATION_DIRECTORY_PATH = realpath(realpath(dirname(Base.find_package("OMParser")) * "/../"))

"""
"""
const BUILD_DIRECTORY_PATH = joinpath(INSTALLATION_DIRECTORY_PATH, "lib", "build", "lib")
const SHARED_DIRECTORY_PATH = joinpath(INSTALLATION_DIRECTORY_PATH, "lib", "ext", "shared")

struct ParseError
end

function isDerCref(exp::Absyn.Exp)::Bool
  @match exp begin
    Absyn.CALL(Absyn.CREF_IDENT("der",  nil()), Absyn.FUNCTIONARGS(Absyn.CREF(__) <|  nil(),  nil()), nil())  => true
    _ => false
  end
end

function _parser_library_suffix()
  if Sys.islinux()
    return ".so"
  elseif Sys.iswindows()
    return ".dll"
  end
  return ".dylib"
end

"""
  Locate a parser library below a root directory.
"""
function locateSharedParserLibrary(directoryToSearchIn)
  isdir(directoryToSearchIn) || return nothing
  suffix = _parser_library_suffix()
  for (root, _, files) in walkdir(directoryToSearchIn)
    for file in files
      if occursin("libomparse-julia", file) && endswith(file, suffix)
        return joinpath(root, file)
      end
    end
  end
  return nothing
end

const _libpath = if Sys.iswindows()
  locateSharedParserLibrary(BUILD_DIRECTORY_PATH)
elseif Sys.islinux()
  locateSharedParserLibrary(BUILD_DIRECTORY_PATH)
elseif Sys.isapple()
  locateSharedParserLibrary(BUILD_DIRECTORY_PATH)
else
  throw("Your system is not supported. Supported Systems are Linux, macOS and Windows.")
end

#= Lib path for externally downloaded parser libraries =#
const libpath = if Sys.iswindows()
  locateSharedParserLibrary(SHARED_DIRECTORY_PATH)
elseif Sys.islinux()
  locateSharedParserLibrary(SHARED_DIRECTORY_PATH)
elseif Sys.isapple()
  locateSharedParserLibrary(SHARED_DIRECTORY_PATH)
else
  throw("Your system is not supported. Supported Systems are Linux, macOS and Windows.")
end


#= If there exists a prebuilt library we use that. Otherwise we use the precompiled binary generated by Pkg.build =#
const installedLibPath = if _libpath != nothing
    _libpath
  else
    libpath
end

"""
langStd:
 ("1.x", 10), ("2.x", 20), ("3.0", 30), ("3.1", 31), ("3.2", 32), ("3.3", 33),
 ("3.4", 34), ("3.5", 35), ("latest",1000), ("experimental", 9999)
 acceptedGram:
 1=Modelica, 2=MetaModelica, 3=ParModelica, 4=Optimica, 5=PdeModelica
"""
function parseString(contents::String,
                     interactiveFileName::String = "<default>",
                     acceptedGram::Int64 = 1,
                     languageStandard::Int64 = 1000)::Absyn.Program
  local res = ccall((:parseString, installedLibPath), Any, (String, String, Int64, Int64), contents, interactiveFileName, acceptedGram, languageStandard)
  if res == nothing
    throw(ParseError())
  end
  res
end

"""
```
parseFile(fileName::String, acceptedGram::Int64 = 1, languageStandard::Int64 = 9999)::Absyn.Program
```

Parse a file according to a grammar and a language standard.

 Language standard mapping for the `languageStandard` argument:
```
 ("1.x", 10), ("2.x", 20), ("3.0", 30), ("3.1", 31), ("3.2", 32), ("3.3", 33),
 ("3.4", 34), ("3.5", 35), ("latest",1000), ("experimental", 9999)
```

Grammar mapping for the `acceptedGram` variable:
```
 1=Modelica, 2=MetaModelica, 3=ParModelica, 4=Optimica, 5=PdeModelica
```
"""
function parseFile(fileName::String, acceptedGram::Int64 = 1, languageStandard::Int64 = 9999)::Absyn.Program
  local res = ccall((:parseFile, installedLibPath), Any, (String, Int64, Int64), fileName, acceptedGram, languageStandard)
  if res == nothing
    throw(ParseError())
  end
  res
end

end
